### ISSUE TITLE
In PSGallery, this project's link to the repo is 404

### ISSUE THREAD

**Issue by doctordns** [jborean93/PowerShell-OpenAuthenticode#6]
If you view this project in the PS Gallery: https://www.powershellgallery.com/packages/OpenAuthenticode/0.2.0 there is a line to the 'Project SIte". Clickin on this generates a 404.

**Comment by jborean93** [comment]
Thanks for the issue, this was fixed with https://github.com/jborean93/PowerShell-OpenAuthenticode/commit/11e21d87d59e75d8d7967ebe7a371347540f1d83 and is just waiting for a new release.
